api:
  id: "20128925"  
  
http:
  host: "0.0.0.0"
  port: "8081"

request:
  ihubSapi:
    host: "ihub-sapi-2tjdvy.5sc6y6-4.usa-e2.cloudhub.io"
    port: "443"
    
ihubSapi:
  clientId: "![Qb21avQsZIDyQvJEJEU8PfkAHS8rlZFYw+q+AK7Au7DB0BPsdPg/Gg==]"
  clientSecret: "![c3TmWKU1w4vTJn7LafFJMWzuXw//qWUSSeP6S53pDjikf9etJY4ypA==]"      
  
